puts ("add operator") 
puts(7 + 4)    
puts ("subtract operator")
puts(13 - 5)    
puts ("multiply operator")
puts(4 * 8)    
puts ("divide operator")
puts(11 / 3)   
puts ("raise to a power operator")
puts(12**2)    
puts ("modulo operator")
puts(16 % 5) 